name: Handle Issues
on: push
jobs:
    output-info:
        runs-on: ubuntu-latest
        steps:
          - name: Output Events Details
            run: echo "$ toJson{{ github.event }}" #Github context objects